FROM alpine/git

ENV TZ="Europe/Berlin"
ENV GIT_SSL_CAINFO="/usr/local/share/ca-certificates/OrgaCard-Root-CA.crt"

USER 0:0
COPY OrgaCard-Root-CA.pem /usr/local/share/ca-certificates/OrgaCard-Root-CA.crt
